language: python
python:
  - "3.5"
  - "3.6"
env:
  -DJANGO=2.2.2
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run --source='.' manage.py test employee
# send coverage report to coveralls
after_success:
  - coveralls