# Generated by Django 2.2.2 on 2019-06-26 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('email', models.EmailField(db_index=True, max_length=120, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=140)),
                ('department', models.CharField(max_length=100)),
            ],
        ),
    ]
